bug-fix: error calling YAML.Load() with callback
Node.js doc says: "If no encoding is specified, then the raw buffer is returned."
http://nodejs.org/api/fs.html#fs_fs_readfile_filename_options_callback

Thus I had:
Uncaught node.js Error

TypeError: Object [object Object] has no method 'split'
at Object.YamlParser.cleanup (yamljs/bin/yaml.js:1589:17)
at Object.YamlParser.parse (yamljs/bin/yaml.js:980:21)
at Object.Yaml.parse (yamljs/bin/yaml.js:240:15)
at yamljs/bin/yaml.js:215:24
at yamljs/bin/yaml.js:309:22
at fs.js:266:14

with Node.js v0.10.12